version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
    volumes:
      - /var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - database

  user-service:
    image: user-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    depends_on:
      - postgres
    volumes:
      - /data/user-service
    networks:
      - database
      - network

networks:
  database:
    driver: bridge
  network:
    driver: bridge
