version: '3'

services:
  user-db:
    image: postgres
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
    volumes:
      - /var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - user-database

  user-service:
    image: user-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - 8083:8083
    volumes:
      - /data/user-service
    networks:
      - user-database
      - network

networks:
  user-database:
    driver: bridge
  network:
    driver: bridge
