= User Service

Service responsible for managing users and login.

== Tech-Stack
The user service is based on the Spring Framework with Webflux and Netty as its HTTP-server stack and ActiveMQ connections as message broker. The service is connected to dedicated PostgreSQL database, where data is persisted.

== Database / PostgreSQL
The database holds all information of registered users.

== HTTP API
The API is documented as OpenAPI Specification in https://git.thm.de/microservicesss21/user-service/-/blob/master/user-service.yaml[user-service.yaml]

== Message-Broker / ActiveMQ
It is sending out events whenever a user is created, updated or deleted.

The user service is not listening to any ActiveMQ topic.

== Login
The login to the system is realized via HTTP-Basic auth to /login. After that a JWT is issued which contains all relevant information about the user. The JWT is valid for a limited period of time. A reissue mechanism or a blacklist is not (yet) implemented.

== Further Reading
Please refer to the https://git.thm.de/microservicesss21/orga/-/blob/master/README.md[README] of the Orga-Repository for more information.
This service uses the https://git.thm.de/microservicesss21/service-lib/-/blob/master/README.md[service-lib] as a dependency.
